# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 17:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nips', '0002_auto_20170720_1744'),
        ('siren', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siren',
            name='acceptable_bounds_lower_limit',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='siren',
            name='acceptable_bounds_upper_limit',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='siren',
            name='message',
            field=models.CharField(default='Monitored variable out of bounds.', max_length=100),
        ),
        migrations.AddField(
            model_name='siren',
            name='monitor_variable',
            field=models.CharField(default='temperature', max_length=30),
        ),
        migrations.AddField(
            model_name='siren',
            name='nip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nips.Nip'),
        ),
        migrations.AddField(
            model_name='siren',
            name='tolerance',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='siren',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='siren.Siren'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
