# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siren', '0004_siren_circular_buffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='siren',
            name='number_of_issues',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='siren',
            name='status',
            field=models.CharField(choices=[('D', 'Dormant'), ('A', 'Alert')], default='D', max_length=1),
        ),
    ]
