# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 11:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siren', '0006_auto_20170726_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='siren',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='siren.Siren'),
        ),
    ]
