# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 12:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('siren', '0008_auto_20170726_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='siren',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
        migrations.RenameField(
            model_name='siren',
            old_name='number_of_issues',
            new_name='past_number_of_alerts',
        ),
        migrations.AddField(
            model_name='siren',
            name='email_notification',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='siren',
            name='text_notification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='siren',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
