# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 13:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siren', '0009_auto_20170726_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('handled_datetime', models.DateTimeField(blank=True)),
                ('comments', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='siren',
            name='past_number_of_alerts',
        ),
        migrations.AlterField(
            model_name='siren',
            name='status',
            field=models.CharField(choices=[('D', 'Dormant'), ('P', 'Paused'), ('A', 'Alert')], default='D', max_length=1),
        ),
        migrations.AddField(
            model_name='alert',
            name='siren',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='siren.Siren'),
        ),
    ]
