# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 13:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('siren', '0010_auto_20170726_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siren',
            name='user',
        ),
        migrations.AddField(
            model_name='siren',
            name='user',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
