# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 13:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('siren', '0011_auto_20170726_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siren',
            name='user',
        ),
        migrations.AddField(
            model_name='siren',
            name='creator',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='siren',
            name='registered_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
