# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siren', '0013_auto_20170726_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('S', 'Seen'), ('H', 'Handled')], default='A', max_length=1),
        ),
    ]
