# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 08:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siren', '0015_auto_20170727_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='handled_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alert',
            name='seen_by',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
