# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-19 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NipRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_directory', models.CharField(default='', max_length=20)),
                ('nip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nips.Nip')),
            ],
        ),
    ]
