# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nips', '0002_auto_20170720_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='nip',
            name='status',
            field=models.CharField(choices=[('AA', 'Awaiting Activation'), ('W', 'Working'), ('D', 'Disabled'), ('E', 'Error')], default='AA', max_length=2),
        ),
    ]
