# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nips', '0005_auto_20170725_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='niplocation',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
